---
- name: Evaluate nexus namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: nexus
    state: present

- name: Evaluate nexus Operator Group
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'nexus-operatorgroup.yaml.j2') }}"

- name: Evaluate nexus Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'nexus-subscription.yaml.j2') }}"

- name: Wait for nexus operator to install
  k8s_facts:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: nexus.apps.m88i.io
  register: crd_nexus
  until: nexus.resources | list | length == 1
  retries: 10
  delay: 30