---
- name: Evaluate user{{ item }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: 'user{{ item }}'
    state: present

- name: Evaluate postgres Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'postgres-subscription.yaml.j2') }}"
